name: OCPL Configuration Management Standards Check (Shared)

on:
  workflow_call:

jobs:
  # use commitlint to verify git commit messages
  # settings are in commitlint.config.js
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # 1) Update the run's Summary tab
      - name: Update Job Summary
        run: |
          echo "This branch has been retired; use @workflow/v4 instead." >> "$GITHUB_STEP_SUMMARY"

      # 2) Output the same message in the workflow log
      - name: Print Message
        run: |
          echo "This branch has been retired; use @workflow/v4 instead."

      # 3) Exit with an error
      - name: Fail the run
        run: |
          exit 1